# https://github.com/pipe-cd/pipecd/pkgs/container/piped-base/103341355?tag=v0.44.0-alpha-52-ge881cac
FROM 403302022553.dkr.ecr.ap-northeast-1.amazonaws.com/azurite-piped/piped-base:20230823130625

ADD .artifacts/launcher /usr/local/bin/launcher

ENTRYPOINT ["launcher"]
